spring.application.name=seat-reservation

spring.datasource.url=jdbc:postgresql://localhost:5432/seatreservation
spring.datasource.username=seatuser
spring.datasource.password=seatpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.data-source-properties.options=-c TimeZone=Asia/Kolkata